baseurl = "https://takatsukiiaidou.github.io/"
copyright = "© 2024, 高槻市居合道連盟"
enablerobotstxt = true
languagecode = "en-us"
paginate = 50
titlecasestyle = "Go"

publishDir = "docs"

[languages.en]
title = "高槻市居合道連盟"
description = "高槻市における居合道の普及発展を推進する団体"
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "ホーム"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "activity"
name = "活動"
url = "/activity/"
weight = 20

[[languages.en.menu.main]]
identifier = "class"
name = "教室"
url = "/class/"
weight = 30

[[languages.en.menu.main]]
identifier = "tags"
name = "タグ"
url = "/tags/"
weight = 40

[[languages.en.menu.main]]
identifier = "search"
name = "検索"
url = "/search/"
weight = 100

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "github.com/willfaught/paige"

